spring:
    application:
      name: stokker
server:
  port: 8989  
---

spring:
   profiles: default
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
---
spring:
   profiles: remote-es-node
   data:
       elasticsearch:
           cluster-nodes: localhost:9300
---
spring:
   profiles: heroku
eureka:
    client:
        serviceUrl:
            defaultZone: https://stokker-portfolio-manager.herokuapp.com/eureka/           
