spring:
    application:
      name: stokker
server:
  port: 8989  

---

spring:
   profiles: default
eureka:
    password: user
    client:
        serviceUrl:
            defaultZone: http://user:${eureka.password}@localhost:9999/eureka/
---
spring:
   profiles: remote-es-node
   data:
       elasticsearch:
           cluster-nodes: localhost:9300
---
spring:
   profiles: heroku
eureka:
    password: user
    client:
        serviceUrl:
            defaultZone: https://user:${eureka.password}@stokker-portfolio-manager.herokuapp.com/eureka/           
